### ISSUE TITLE
Head is visible on first person render

### ISSUE THREAD

**Issue by Fleyzi** [ZsoltMolnarrr/BetterCombat#28] opened 2022-07-27 13:53 UTC
While I'm attacking, I can see a head of my character. It's still here when you turning Off option "Showing arms in first person".

Mod Version: 1.0.3 (current)

Here's [latest.log](https://gist.github.com/Fleyzi/e4a954ae5896ed703b86f904e58deb81) file

Screenshots:
![2022-07-27_18 38 15](https://user-images.githubusercontent.com/36078397/181264593-2780db01-584f-4921-b416-cc8289294835.png)
![2022-07-27_18 39 03](https://user-images.githubusercontent.com/36078397/181264605-6f819e77-cd5f-45cd-995b-a2479cd616d4.png)
![2022-07-27_18 39 22](https://user-images.githubusercontent.com/36078397/181264614-2acd99c8-c0b8-41c1-8d47-2f68b682a311.png)

**Comment by ZsoltMolnarrr** [comment] 2022-07-27 14:55
Duplicate of #22
Feel free to reopen the issue, in case uninstalling Twilight Forest doesn't solve the issue.

**Closed by ZsoltMolnarrr** 2022-07-27 14:55 UTC
