### ISSUE TITLE
kick from server when attack with weapon in inventorio slot

### ISSUE THREAD

**Issue by NEOLEE98** [ZsoltMolnarrr/BetterCombat#43] opened 2022-08-08 17:50 UTC
Not happened all the time, but sometimes the server kick out the player with error below when using a weapon from the inventorio mod's weapon slot, the server didn't crash
```
[13:35:27] [Netty Server IO #20/ERROR]: Encountered exception while handling in channel with name "bettercombat:c2s_request_attack"
java.lang.NullPointerException: Cannot invoke "net.bettercombat.logic.AttackHand.attack()" because "hand" is null
	at net.bettercombat.network.ServerNetwork.lambda$initializeHandlers$6(ServerNetwork.java:73) ~[bettercombat-1.0.10+1.19.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.receive(ServerPlayNetworkAddon.java:89) ~[fabric-networking-api-v1-1.1.0+442de8b8a9-4071c58cedb5d399.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.receive(ServerPlayNetworkAddon.java:38) ~[fabric-networking-api-v1-1.1.0+442de8b8a9-4071c58cedb5d399.jar:?]
	at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.handle(AbstractChanneledNetworkAddon.java:100) [fabric-networking-api-v1-1.1.0+442de8b8a9-4071c58cedb5d399.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.handle(ServerPlayNetworkAddon.java:84) [fabric-networking-api-v1-1.1.0+442de8b8a9-4071c58cedb5d399.jar:?]
	at net.minecraft.class_3244.handler$bgk000$handleCustomPayloadReceivedAsync(class_3244.java:2383) [server-intermediary.jar:?]
	at net.minecraft.class_3244.method_12075(class_3244.java) [server-intermediary.jar:?]
	at net.minecraft.class_2817.method_12199(class_2817.java:38) [server-intermediary.jar:?]
	at net.minecraft.class_2817.method_11054(class_2817.java:7) [server-intermediary.jar:?]
	at net.minecraft.class_2535.method_10759(class_2535.java:171) [server-intermediary.jar:?]
	at net.minecraft.class_2535.method_10770(class_2535.java:156) [server-intermediary.jar:?]
	at net.minecraft.class_2535.channelRead0(class_2535.java:54) [server-intermediary.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) [netty-transport-4.1.76.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.76.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.76.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.76.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.76.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) [netty-codec-4.1.76.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.76.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.76.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.76.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.76.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) [netty-codec-4.1.76.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.76.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.76.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.76.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.76.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) [netty-codec-4.1.76.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.76.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.76.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.76.Final.jar:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-codec-4.1.76.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.76.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.76.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.76.Final.jar:?]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-handler-4.1.76.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.76.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.76.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.76.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.76.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.76.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.76.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.76.Final.jar:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-transport-4.1.76.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) [netty-transport-4.1.76.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) [netty-transport-4.1.76.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) [netty-transport-4.1.76.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) [netty-transport-4.1.76.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-common-4.1.76.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.76.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by ZsoltMolnarrr** [comment] 2022-08-10 20:46
Duplicate of #42

**Closed as completed by ZsoltMolnarrr** 2022-08-10 20:46 UTC

**Comment by DadoIrie** [comment] 2022-08-16 12:22
@NEOLEE98 hope it ain't too late ... did you resolved it? 
Have the exact some problem and was testing the last days all kinda stuff till decided to give up and wait and hope for a fix ... but that's hard if can't really understand what causes that issue.
Do you still got the log? - because wanna see what mods you were using during that ... if not a list of mods list used when this happened would be also enough

**Comment by NEOLEE98** [comment] 2022-08-16 13:43
@dadoirie I just ended up uninstalling inventorio cause it also bypass levelz

**Comment by DadoIrie** [comment] 2022-08-16 13:49
I'm getting a very similar - if not same - error and have not inventorio installed ... but now removed rpgdifficulty and difficultyplus and it doesn't happen anymore ... now if those are the mods in my case which do conflict with bettercombat it might be a huge help if that can be confirmed and therefore fixing it and making them compatible with bettercombat ... are you on singleplayer or dedicated server?

**Comment by NEOLEE98** [comment] 2022-08-16 13:53
@dadoirie I do have rpgdificulty, haven't run into that error with newest bettercombat after uninstalling inventorio, I'm on a dedicated server.

**Comment by DadoIrie** [comment] 2022-08-16 13:59
> @dadoirie I do have rpgdificulty, haven't run into that error with newest bettercombat after uninstalling inventorio, I'm on a dedicated server.

well - I was wrong ... just now that crash happened again 👎 my theory got nullified and trampled and ... damn it
