### ISSUE TITLE
Problem with the first person when i attack 

### ISSUE THREAD

**Issue by Deagox** [ZsoltMolnarrr/BetterCombat#207] opened 2023-02-19 08:56 UTC
**1.18.2** - ?
**40.1.73** - ?
**1.5.5** - ?
**I am using the latest version available** - ?

**Describe the bug**

**To Reproduce**
4. See er
![2023-02-19_09 22 49] (https://user-images.githubusercontent.com/64354034/219938337-af5176b1-b929-4d34-8ac2-6880d473d2f8.png)
ror

**Expected behavior**

**Screenshots or video recordings**

**Additional context**

**Comment by ZsoltMolnarrr** [comment] 2023-02-19 10:08
Better Combat discord FAQ:
**Whenever I swing a weapon in First person, my head shows up and it  blocks the screen fully. How to fix?**
This kind of problem is typically caused by another mod that handles renderstates in a faulty way.
Many of these (formerly incompatible) mods have been fixed in the recent months. Please try updating all of the installed mods.
Usual suspects: Twilight Forest (fixed with update), Minecraft Comes Alive Reborn (issue still open)

**Closed as completed by ZsoltMolnarrr** 2023-02-19 10:08 UTC
