### ISSUE TITLE
body visible in first person in multiplayer

### ISSUE THREAD

**Issue by harithmf** [ZsoltMolnarrr/BetterCombat#230] opened 2023-03-25 20:55 UTC
**Minecraft version** - ? 1.19.3
**Mod loader** - ? fabric
**Mod version** - ? latest
**I am using the latest version available** - ? yes

**Describe the bug**
in first person, when looking at another player, swing sword and my character head is into view

**To Reproduce**

**Expected behavior**

**Screenshots or video recordings**

**Additional context**

**Comment by drakosoldier298** [comment] 2023-03-25 22:15
Sounds like you are using first person player model mod which causes this, 

Also im not a dev im just a player that was wandering the github

**Comment by harithmf** [comment] 2023-03-25 23:47
> Sounds like you are using first person player model mod which causes this,
> 
> Also im not a dev im just a player that was wandering the github

not using any first person player mod.

**Comment by ZsoltMolnarrr** [comment] 2023-04-07 10:52
Better Combat FAQ:

**Whenever I swing a weapon in First person, my head shows up and it  blocks the screen fully. How to fix?**
This kind of problem is typically caused by another mod that handles renderstates in a faulty way.
Many of these (formerly incompatible) mods have been fixed in the recent months. Please try updating all of the installed mods.
Usual suspects: Twilight Forest (fixed with update), Minecraft Comes Alive Reborn (issue still open)

**Closed as completed by ZsoltMolnarrr** 2023-04-07 10:52 UTC
