### ISSUE TITLE
game crash malum conflict

### ISSUE THREAD

**Issue by helicoprion1** [ZsoltMolnarrr/BetterCombat#95] opened 2022-09-02 17:55 UTC
**Minecraft version** - 1.18.2
**Mod loader** - forge
**Mod version** -
 8/31/2022  bettercombat-forge-1.2.1+1.18.2.jar

6/19/2022  malum-1.18.2-1.3.7.jar
**I am using the latest version available** - yes

**Describe the bug**
the only thing about this bug that I understand is that if you use either scythe from malum and kill an enemy with it the game crashes and continues to crash upon an attempt to join the world (both single and multiplayer)
it does this even with the "rebounding" enchantment

**To Reproduce**
1. install both malum and better combat
2. kill anything with the scythe
3. this capacity error generates different numbers each time
The game crashed whilst unexpected error
Error: java.lang.IllegalArgumentException: newLimit > capacity: (9184 > 1536)

**Expected behavior**

**Screenshots or video recordings**
i don't have a screenshot but the last frame is always the enemy being destroyed and the spirit drops spawning

**Additional context**
my only guess is that the game is expecting a certain number of loot drops and because the scythe creates the soulshards/spirit items with no looting enchantment or the like its flipping out

**Comment by ZsoltMolnarrr** [comment] 2022-09-02 17:56
Hello!
Please provide a crashlog file.

**Comment by chronosacaria** [comment] 2022-09-02 19:41
Just figured that I'd mention that I cannot reproduce this crash and I only have Better Combat, Malum and their respective dependencies

**Comment by ZsoltMolnarrr** [comment] 2022-09-06 18:41
I cannot reproduce any crash with Better Combat and Malum, so I have to close this issue.

**Closed as completed by ZsoltMolnarrr** 2022-09-06 18:41 UTC
