### ISSUE TITLE
mismatch

### ISSUE THREAD

**Issue by Rogenar** [ZsoltMolnarrr/BetterCombat#188] opened 2023-01-21 11:31 UTC
version bettercombat-fabric-1.5.4+1.19.3 causes incompatibility with inventorio mod, causing me to choose between the two. Will there be an updated version that works in harmony with the Inventorio mode?

**Comment by ZsoltMolnarrr** [comment] 2023-01-21 11:32
Duplicate of https://github.com/ZsoltMolnarrr/BetterCombat/issues/42

**Closed as completed by ZsoltMolnarrr** 2023-01-21 11:32 UTC
