### ISSUE TITLE
Axe cannot be used as a tool with isMiningWithWeaponsEnabled set to false

### ISSUE THREAD

**Issue by MarioSMB** [ZsoltMolnarrr/BetterCombat#171] opened 2022-12-12 10:05 UTC
**Minecraft version** - 1.18.2
**Mod loader** - Forge
**Mod version** - 40.1.86
**I am using the latest version available** - 1.5.2

**Describe the bug**
With `"isMiningWithWeaponsEnabled": false,` in the client configuration, axes can no longer be used to break blocks, as they are treated like a weapon.

**To Reproduce**
N/A

**Expected behavior**
When this option is set to false, perhaps items marked as tools should still behave as if it's enabled?

**Screenshots or video recordings**
![2022-12-12_19 59 54](https://user-images.githubusercontent.com/1998392/207017169-481f5a90-63fc-4238-8908-50641f966dc7.png)

**Additional context**
#163 seems related but it's mentioned there that it *definitely works*, so I'm assuming this is a different issue.

**Comment by ZsoltMolnarrr** [comment] 2022-12-12 10:34
Works as intended.

**Comment by MarioSMB** [comment] 2022-12-12 11:03
That is quite strange, since the feature is completely unusable due to this issue - being able to break blocks is a fundamental part of the game.

**Comment by ZsoltMolnarrr** [comment] 2022-12-12 11:13
This is a soft implementation of Battle mode, even a hotkey can be assigned to it.
Nothing to change in this regard.

**Closed as completed** 2022-12-12 11:14 UTC

**Comment by Sockies** [comment] 2023-04-08 01:14
This is a source of major frustration for me. I have to choose between not being able to use axes, or accidentally mining blocks instead of starting a swing.

I hear that a hotkey can be assigned to it, but I'm unsure how to do that. Are there any workarounds that I could add to my config? Perhaps an extra config option can be added that allows axes to be excluded from the weapon category.

**Comment by tsokiyZan** [comment] 2024-09-15 06:58
This dev has repeatedly shown that he has no regard for what his community wants at all, this is a cool mod but this issue along with a few others lead me to not include it in many modpacks, and also afaik, there is no way to add a hotkey to this even though we really shouldn't have to in the first place

**Comment by MarioSMB** [comment] 2024-09-15 08:21
Arguably axes (along with other tools) should *not* have a special attacking animation, as it just makes using them as tools far too inconvenient.  

As such, I would suggest that anyone looking back at this issue (which is probably a lot of people) simply add `axe` to the regex blacklist in config.

**Comment by ZsoltMolnarrr** [comment] 2024-09-15 08:56
There are multiple solutions:
1. Disable Better Combat attacks for axes, by removing them from fallback compatibility
2. Toggling Mine with Weapons
