### ISSUE TITLE
Server crashing at launching with this mod

### ISSUE THREAD

**Issue by Kaiizer261** [ZsoltMolnarrr/BetterCombat#208] opened 2023-02-20 16:38 UTC
**Minecraft version** - 1.18.2
**Mod loader** - Forge 40.2.0
**Mod version** - 1.5.5
**I am using the latest version available** - Yes

**Describe the bug**
I created my server with the forge server installer.
As soon as I start my own server (which I created to play with friends), it crashes. In the server mod file, I only put the mods: Better Combat, Cloth config, Player animation lib. 
I don't really know if I did something wrong when I created the server or if it's the mod that makes it crash.
I put the log message down below :

-------------
[20févr.2023 17:06:02.316] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 40.2.0, --fml.mcVersion, 1.18.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220404.173914]
[20févr.2023 17:06:02.321] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 9.1.3+9.1.3+main.9b69c82a starting: java version 19.0.2 by Oracle Corporation
[20févr.2023 17:06:02.448] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/PC/Desktop/Serveur%20RPG%2019-03-23/serveur%20moddé/Recherche%20minecraft%20serv/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2314!/ Service=ModLauncher Env=SERVER
[20févr.2023 17:06:02.804] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\PC\Desktop\Serveur RPG 19-03-23\serveur moddé\Recherche minecraft serv\libraries\net\minecraftforge\fmlcore\1.18.2-40.2.0\fmlcore-1.18.2-40.2.0.jar is missing mods.toml file
[20févr.2023 17:06:02.811] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\PC\Desktop\Serveur RPG 19-03-23\serveur moddé\Recherche minecraft serv\libraries\net\minecraftforge\javafmllanguage\1.18.2-40.2.0\javafmllanguage-1.18.2-40.2.0.jar is missing mods.toml file
[20févr.2023 17:06:02.819] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\PC\Desktop\Serveur RPG 19-03-23\serveur moddé\Recherche minecraft serv\libraries\net\minecraftforge\lowcodelanguage\1.18.2-40.2.0\lowcodelanguage-1.18.2-40.2.0.jar is missing mods.toml file
[20févr.2023 17:06:02.826] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\PC\Desktop\Serveur RPG 19-03-23\serveur moddé\Recherche minecraft serv\libraries\net\minecraftforge\mclanguage\1.18.2-40.2.0\mclanguage-1.18.2-40.2.0.jar is missing mods.toml file
[20févr.2023 17:06:02.938] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator/]: No dependencies to load found. Skipping!
[20févr.2023 17:06:04.409] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[20févr.2023 17:06:04.414] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeserver' with arguments []
[20févr.2023 17:06:04.564] [main/WARN] [mixin/]: Error loading class: net/minecraft/world/item/ItemStack (java.lang.IllegalArgumentException: Unsupported class file major version 63)
[20févr.2023 17:06:04.565] [main/WARN] [mixin/]: @Mixin target net.minecraft.world.item.ItemStack was not found bettercombat.mixins.json:ItemStackMixin
[20févr.2023 17:06:04.636] [main/WARN] [mixin/]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Unsupported class file major version 63)
[20févr.2023 17:06:05.434] [main/WARN] [mixin/]: Error loading class: java/lang/Double (java.lang.IllegalArgumentException: Unsupported class file major version 63)
-----------

I can also say that with some other mods, like Terralith, the server works.

**To Reproduce**
1. Start the run.bat file
2. Then, the crash/error appears

![screenshot2](https://user-images.githubusercontent.com/125904344/220161073-cfe9a3d9-ebd6-46ac-8bb4-a6d14c0155d0.png)
![Screenshot](https://user-images.githubusercontent.com/125904344/220161094-bd90f472-7b08-4597-b379-55895c071c53.png)

**Comment by ZsoltMolnarrr** [comment] 2023-02-20 16:42
Hello!
These error logs don't show any specific reference to Better Combat, nor can I reproduce the error.
I recommend going through the troubleshooting guide on our Discord server.
Closing this issue due to lack of actionable data.

**Closed as completed by ZsoltMolnarrr** 2023-02-20 16:42 UTC
