### ISSUE TITLE
Using better combat in a server causing player to get kick.

### ISSUE THREAD

**Issue by Duplicate34** [ZsoltMolnarrr/BetterCombat#213] opened 2023-02-25 05:37 UTC
**Minecraft version** - 1.19.3
**Mod loader** - Forge 1.19.3-44.1.0
**Mod version** - 1.5.5
**I am using the latest version available** - Yes

**Describe the bug**
Note: The mod works fine in single player

So I am using these mods:
[1.19.3]-Epic-Knights-Armor-and-Weapons-6.7v.jar
alexsmobs-1.22.0
citadel-2.2.3-1.19.3
cloth-config-9.0.94-forge
journeymap-1.19.3-5.9.3-forge
bettercombat-forge-1.5.5+1.19.3
player-animation-lib-forge-0.4.2+1.19.3

So upon joining the server similar mods using any attack with weapons that have animations in the better combat mod will cause the player to crash the error message: Internal Exception: java.lang.ArrayIndexOutOfBoundsException: Index 3039845 out of bounds for length 3

**To Reproduce**

Join a server with a mod install
Hold attack with any weapon

**Comment by ZsoltMolnarrr** [comment] 2023-02-25 15:07
I cannot reproduce the problem.
Could you please provide some actionable data?

**Comment by Duplicate34** [comment] 2023-02-26 20:12
So I'm using aternos server and rehosting the server since we just move back to 1.19.2 for the mod to work but this what happen when I try to use the mod.
https://user-images.githubusercontent.com/126309910/221434473-377c92f4-5586-49d9-828d-8906c8123e66.mp4

**Comment by ZsoltMolnarrr** [comment] 2023-03-06 16:50
Non reproducible, non actionable report. Closing.

**Closed as completed by ZsoltMolnarrr** 2023-03-06 16:50 UTC
