### ISSUE TITLE
mismatch

### ISSUE THREAD

**Issue by Rogenar** [ZsoltMolnarrr/BetterCombat#250] opened 2023-05-11 21:18 UTC
![ss2](https://github.com/ZsoltMolnarrr/BetterCombat/assets/122460325/4b1bd9a2-556d-4f84-a1f5-56a86eea07ca)

**Comment by ZsoltMolnarrr** [comment] 2023-05-11 21:20
Duplicate of #42

**Closed as completed by ZsoltMolnarrr** 2023-05-11 21:20 UTC

**Comment by Rogenar** [comment] 2023-05-11 21:21
Will there be a version to fix this?

**Comment by ZsoltMolnarrr** [comment] 2023-05-11 21:22
Yes breaks flag will be lifted if new version of Inventorio is verified to have no issues.
