### ISSUE TITLE
Most recent release crashes

### ISSUE THREAD

**Issue by Aceplante** [ZsoltMolnarrr/BetterCombat#218] opened 2023-02-27 04:01 UTC
I just downloaded this but it crashes on start. Im using forge 1.18.2

**Comment by sentwayfarer** [comment] 2023-02-27 05:46
Any logs? Forge version?

**Comment by Aceplante** [comment] 2023-02-27 08:32
Yes, forge 1.18.2 i dont have the logs rn

**Comment by ZsoltMolnarrr** [comment] 2023-02-27 08:48
Closing issue due to lack of actionable data.
The issue cannot be reproduced with an automatically managed installation (CurseForge launcher).
I recommend updating all mods to the latest version (especially PlayerAnimator).

**Closed as completed by ZsoltMolnarrr** 2023-02-27 08:48 UTC

**Comment by ZsoltMolnarrr** [comment] 2023-02-27 09:33
Your report is valid, the problem comes down to Forge mods.toml file, which I forgot to update.
That would make Forge require new version of PlayerAnimator. This will be fixed in next release.
Until then, it still works, you just don't get the correct error message.

**Comment by Aceplante** [comment] 2023-02-27 23:23
I dont get any error message though, the game completely crashes
