### ISSUE TITLE
[Forge 1.18.2] Twilight Forest - Head visible First Person mode

### ISSUE THREAD

**Issue by manyogurt** [ZsoltMolnarrr/BetterCombat#64] opened 2022-08-24 21:05 UTC
**Minecraft version** - 1.18.2
**Mod loader** - Forge
**Mod version** - 1.1.0
**I am using the latest version available** - Yes

**Describe the bug**
When I swing my weapon in first person mode, I can see the inside and outside of my head.

**To Reproduce**

Swing a weapon when in minecraft and in first person mode

**Expected behavior**
I expected to not see my head

**Screenshots or video recordings**
![2022-08-24_22 52 17](https://user-images.githubusercontent.com/44836817/186521559-aa0c7c6e-8d2e-442d-ab2d-32646d9b77ed.png)

![2022-08-24_22 52 14](https://user-images.githubusercontent.com/44836817/186521594-65fcac8c-e5cb-4d62-8539-a033088062de.png)

**Additional context**

**Comment by Reimnop** [comment] 2022-08-25 08:45
Do you have Twilight Forest? If so, have you tried removing it?
Removing Twilight Forest fixed it for me

**Comment by Corwin00420** [comment] 2022-08-25 12:02
I also had this issue and can confirm twilight forest was the issue. Not sure what TF does with the character model though.

**Comment by InsaanNotFound** [comment] 2022-08-25 17:24
It should be mentioned that the issue is fixed in 1.19; 1.18 won't be receiving TF updates anymore, according to the author. The issue is rooted in their trophy renderer.

**Comment by ZsoltMolnarrr** [comment] 2022-08-25 18:10
Verified, true.

**Comment by ZsoltMolnarrr** [comment] 2022-08-25 18:37
Contacted Twilight Forest devs.
https://discord.com/channels/313006291012288521/373298308178771978/1012430334773710969

**Comment by KyMann** [comment] 2022-08-26 03:31
The issue also seems to be affecting Fabric installs for 1.18.2. I just noticed it and curseforge user
PeponcioArt seconded.

**Comment by Reimnop** [comment] 2022-08-26 04:22
For Fabric you can just update Twilight Forest

**Comment by ZsoltMolnarrr** [comment] 2022-08-26 15:23
Looks like Team Twilight Forest is working on the issue.
https://github.com/TeamTwilight/twilightforest/commit/e4ae797cfc2c57d1fc68d738d43fb3d6a26d5cfc

Big props for them!

**Comment by ZsoltMolnarrr** [comment] 2022-08-26 15:28
The issue was fixed by the latest release of Twilight Forest.
https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest/files/3952837

**Closed as completed by ZsoltMolnarrr** 2022-08-26 15:28 UTC
Labels: waiting for release, render, incompatibility
