### ISSUE TITLE
Incompability with Kelvin's Better Player Animations

### ISSUE THREAD

**Issue by ghost** [ZsoltMolnarrr/BetterCombat#219] opened 2023-02-27 21:25 UTC
**Minecraft version** - 1.19.3
**Mod loader** - Fabric loader 0.14.14
**Mod version** - 1.6.1
**I am using the latest version available** - Yes

**Describe the bug**
When Kelvin's better animations installed, when I'm using weapons in first person I see my own head and can't see what's happenning behind it
**To Reproduce**
1. Install Better Combat and Kelvin's Better Player Animations
2. Get any supported weapon
3. Click LMB

**Comment by ZsoltMolnarrr** [comment] 2023-03-06 16:53
I am sorry you are having issues.
Better Combat no longer has code related to First Person rendering. This has been moved to PlayerAnimator.

Judging by the issues of Kelvin's Better Player Animations open issues, it looks like the problem is on their end.
I am closing the issue, because there is absolutely zero action I take in Better Combat repository.

**Closed as completed by ZsoltMolnarrr** 2023-03-06 16:53 UTC
