### ISSUE TITLE
Armor shows when swinging weapon

### ISSUE THREAD

**Issue by SugmaLikeSlugma** [ZsoltMolnarrr/BetterCombat#373] opened 2024-06-12 00:07 UTC
**Minecraft version** - 1.20.1
**Mod loader** - Fabric
**Mod version** - 1.8.5
**I am using the latest version available** - yes

**Describe the bug**
When swinging a one-handed weapon (or two one-handed weapons) armor is shown without the rest of my body.

**To Reproduce**

**Expected behavior**

**Screenshots or video recordings**
(https://github.com/ZsoltMolnarrr/BetterCombat/assets/132790965/eeb01e42-d0f9-4b6d-8073-5906674ca655)

**Additional context**

**Comment by SugmaLikeSlugma** [comment] 2024-06-12 00:08
Sorry for not posting steps to reproduce. I don't know whats causing it.

**Comment by ZsoltMolnarrr** [comment] 2024-06-12 08:30
This kind of problem is typically caused by another mod that handles renderstates in a faulty way.
Many of these (formerly incompatible) mods have been fixed in the recent months. Please try updating all of the installed mods.
Usual suspects: Twilight Forest (fixed with update), Minecraft Comes Alive Reborn (issue still open), Heads.

**Closed as completed by ZsoltMolnarrr** 2024-06-12 08:30 UTC
