### ISSUE TITLE
Bug with the Inventorio mod(forge)

### ISSUE THREAD

**Issue by El0wki** [ZsoltMolnarrr/BetterCombat#153] opened 2022-11-12 00:27 UTC
Hey there. If have both Better Combat and Inventorio installed in forge 1.18.2, there is a bug that whenever i press F to swap an item from my offhand to my hand, the item simply disappears.

**Comment by ZsoltMolnarrr** [comment] 2022-11-12 10:29
Duplicate of #42
There is nothing I can do to fix it. Please don't use Inventorio.

**Closed as completed by ZsoltMolnarrr** 2022-11-12 10:29 UTC
