### ISSUE TITLE
[Forge 1.18.2] Minecraft Comes Alive mod - First person

### ISSUE THREAD

**Issue by Razzyreather** [ZsoltMolnarrr/BetterCombat#94] opened 2022-09-01 09:11 UTC
Minecraft version - 1.18.2
Mod loader - forge 40.1.51
Mod version- bettercombat-forge-1.1.1+1.18.2.jar

Clip of the bug happening:
(https://medal.tv/games/minecraft/clips/z46vYdV8LkLyU/d1337W8oYeaJ?invite=cr-MSxvSVcsMjAwNjcxMzIs)

and idk if it has to do with shaders but im using drdestins minecraft shaders

this might be pointless because I'm literally just using a modpack i made with 130 mods but here is this:
abnormals delight
additional guns
advanced compass
alcocraft
alex's delight
alex's mobs
amplified nether
aquaculture
architectury
atlas library
awesome dungeon end
bad mobs
balm
**better combat**
better third person
biome makeover
biomes o plenty
blueprint
buzzier bees
caelus 
camo creepers
cgm
champions
chat heads
chunk animator
cinderscapes
citadel
cloth config
clumps
cold sweat 
collective
comforts
configured
corn delight
coroutil
corpse
cosmetic armor reworked
craftable eggs
crated vanilla foods
creative core
CTOV
cultural delights
curios 
darker depths
true darkness
diet
delightful
domestication innovation
durability tooltip
dusk
dynamic trees 
dynamic trees BOP
elevatorid
enchanting infuser
end additions
end remastered 
enhanced celestials
enhanced visuals
eyes in the darkness
fabricbiomeapireforged
farmers delight
farmers respite
first aid
framework
geckolib
global xp
hardcore torches
hardcore revival
honey expansion
hostile villages
improved mobs
incontrol
inventory essentials
item physics
JEI
kobolds
largemeals
lava monster
library ferret
lootr
lostcities
minecraft comes alive
mmlib
mob sunscreen
modnametooltip
monstereggs
morezombievillagers
mouse tweaks
mutil
neapolitan
nether portal spread
nethers delight
not enough animations
Optifine
passive shield
pehkui
personality
player animation library
puzzles lib
rpgz
seeds
serene seasons
small ships
sophisticated backpacks & core
soundphysics
starter kit
supermartijn642configlib
swing through grass
tenshilib
terrablender
terraform
the graveyard
the graveyard biomes
the wild update mod
the hordes
torohealth
travelers titles
undead expansion
underground villages
unusual drill
unusual end
vbetterbiomes
vmh
simple voice chat
walljump
waystones
whisperwoods
xaeros mini/world map
xercapaint
yungs api
yungs bridges
zombie awareness

**Comment by Razzyreather** [comment] 2022-09-01 09:11
im sorry for this lol

**Comment by ZsoltMolnarrr** [comment] 2022-09-01 11:27
This is a render incompatibility, caused by some other mod. Incorrect state render management of other mods can interfere with the renderer of Better Combat.

Seems like the issue only appears when attacking towards another player.

It would very useful additional information if you could name the conflicting mod.

**Comment by TheGoldenGuardian** [comment] 2022-09-05 05:45
I've had the same issue when playing with a friend and it made the mod basically unusable.
You have Minecraft Comes Alive, same as us, and I believe that to be the culprit since it has its own villager playermodel that overrides the normal one.

A test I did to confirm MCA: I could load into the server with my friend who's already in, and Better Combat renders completely fine until the MCA playermodel loads, then it breaks.

**Comment by ZsoltMolnarrr** [comment] 2022-09-05 13:37
Good feedback, thank you!

**Comment by ZsoltMolnarrr** [comment] 2022-09-07 09:36
I was unable to reproduce the problem using MCA. Does it occur in multiplayer only?

**Comment by TheGoldenGuardian** [comment] 2022-09-07 19:24
Yes, since it's caused by the other player being visible.
Swing while they're not rendered (we were using EntityCulling) and it's completely fine.

**Comment by ShadowsFang** [comment] 2022-09-09 00:26
Can confirm it's not just MCA, having the same issue and the only other mod we share is cosmetic armor

**Comment by SauROnmiKE** [comment] 2022-11-14 07:29
> Can confirm it's not just MCA, having the same issue and the only other mod we share is cosmetic armor

Also happens to me, same issue having multiple mods (MCA & Cosmetic Armor included).

**Comment by ZsoltMolnarrr** [comment] 2023-01-09 12:38
Closing this issue due to not having a specific addressable problem.
Minecraft Comes Alive does not cause such issue when installed with Better Combat.
Feel free to create a new issue if a known, specific combination of mods reproduces this kind of problem.

**Closed as completed by ZsoltMolnarrr** 2023-01-09 12:38 UTC
Labels: render, incompatibility
