### ISSUE TITLE
Improve the animations

### ISSUE THREAD

**Issue by wiisafetymanual** [ZsoltMolnarrr/BetterCombat#433] opened 2024-11-24 23:17 UTC
I love this mods mechanics, as well as how easy and accessible it is to make custom weapons. However, there is a glaring issue with the mod that makes me hesitant to use it despite all of its amazing features. The animations can look very strange when looking up or down, as well as when in motion. When doing both, it doesn't just look strange, it looks completely nonsensical

In most games, attacking up or down mostly just rotates the head, and only slightly rotates the body. This makes the body look much more balanced and natural. For the running while attacking, there could be custom running+attacking animations for each weapon type, that way it matches up with the rotation of the body

If a new animation for every weapon type is too difficult, an easier solution might be to add a config option to make legs unaffected by the attack animations while walking or running. It may look a little strange for some weapon types, but I think that is a tradeoff a lot of players would choose to take

For reference, this is what attacking straight up with a trident looks like (apologies for the darkness)
![2024-11-24_17 48 57](https://github.com/user-attachments/assets/53d45843-c247-4e9b-b70b-3aa42e6dc80d)

**Comment by ZsoltMolnarrr** [comment] 2024-12-10 20:46
Duplicate of #354

**Closed as completed by ZsoltMolnarrr** 2024-12-10 20:46 UTC
