### ISSUE TITLE
[Forge 1.18.2] Crash when adding to a modpack

### ISSUE THREAD

**Issue by BlackAures1** [ZsoltMolnarrr/BetterCombat#68] opened 2022-08-25 12:20 UTC
**Minecraft version** - 1.18.2
**Mod loader** - Forge 1.40.73
**Mod version** - [bettercombat-forge-1.1.0+1.18.2.jar](https://www.curseforge.com/minecraft/mc-mods/better-combat-by-daedelus/files/3949038)

**Describe the bug**
When trying to add to the modpack game crashes at the start.

[crash-2022-08-22_15.53.26-fml.txt](https://github.com/ZsoltMolnarrr/BetterCombat/files/9424541/crash-2022-08-22_15.53.26-fml.txt)

**Comment by Jusey1** [comment] 2022-08-25 15:07
Another crash report using Forge 40.1.73 and this mod. I also tested with 40.1.0 by itself and still crashes. The mod just doesn't work and it seems to have something to do with the SoundUtils.

[crash-2022-08-25_11.03.21-client.txt](https://github.com/ZsoltMolnarrr/BetterCombat/files/9425900/crash-2022-08-25_11.03.21-client.txt)
.

**Comment by ZsoltMolnarrr** [comment] 2022-08-25 17:08
Hello!

None of these errors are looking like Better Combat related.
Looks like the error logs show `fantasyfurniture` as the cause of the error.

**Comment by BlackAures1** [comment] 2022-08-25 22:06
The modpack runs without your mod, but I think it's just some conflict between this 2 mods

**Comment by ZsoltMolnarrr** [comment] 2022-08-26 07:34
If you have EmoteCraft in the modpack, please update that to the latest version.

**Comment by BlackAures1** [comment] 2022-08-26 11:07
There is definitely no EmotCraft here. I am the author of this modpack, if it matters - 
 https://www.curseforge.com/minecraft/modpacks/play-as-dragon 
 
 A list of mods is available here: https://www.curseforge.com/minecraft/modpacks/play-as-dragon/relations/dependencies or here
[modlist.txt](https://github.com/ZsoltMolnarrr/BetterCombat/files/9432595/modlist.txt)

**Comment by ZsoltMolnarrr** [comment] 2022-08-26 14:58
It would be very helpful if you could investigate which mod causes the incompatibility, by enabling/disabling some of them. There is no other way for investigation I know of, since the error log doesn't tell me anything useful.

Unfortunately I don't have time for debugging modpacks.

**Comment by BlackAures1** [comment] 2022-08-26 15:58
Then let's leave this question open for other users, if they encounter a similar problem and want to deal with it in more detail. I have no desire to mess around with it for a long time either, as I'm almost 80% sure it would be functionally/graphically incompatible with the Dragon Survival mod. I wanted to check it out, but alas. I apologize for the inconvenience.

**Comment by Landrozaum** [comment] 2022-08-29 04:52
my game crashed when i tried to test Better Combat with only it installed

**Comment by ZsoltMolnarrr** [comment] 2022-08-29 14:08
This issue contains no useable information that we could use for resolving the issue, no crashlog is referencing Better Combat.
There is nothing I can do for this case.

**Closed as completed by ZsoltMolnarrr** 2022-08-29 14:08 UTC

**Comment by BlackAures1** [comment] 2022-08-30 01:02
No ticket - no problem, as I understand ;)
