### ISSUE TITLE
Visual Head Glitch

### ISSUE THREAD

**Issue by OkScrub** [ZsoltMolnarrr/BetterCombat#212] opened 2023-02-23 03:22 UTC
**Minecraft version** - 1.18.2
**Mod loader** - Fabric And Froge
**Mod version** - 1.5.5
**I am using the latest version available** - Yes

**Describe the bug**
On my sever when we are near 1 of our friends, it causes everyone to be able to see the inside of their head while swinging any weapon making it impossible to fight in first person. We even switched from forge to fabric and it's still the same. Anyone know a fix for this
**To Reproduce**

**Expected behavior**

**Screenshots or video recordings**
https://snipboard.io/Wk9mQP.jpg
**Additional context**
When said friend punches it wont show his play model punching it'll show mine and any animation he does my player will do and vise versa

**Comment by ZsoltMolnarrr** [comment] 2023-02-23 17:06
I am sorry for the inconvenience, there is nothing I can do.
Better Combat discord FAQ address this:

**Whenever I swing a weapon in First person, my head shows up and it  blocks the screen fully. How to fix?**
This kind of problem is typically caused by another mod that handles renderstates in a faulty way.
Many of these (formerly incompatible) mods have been fixed in the recent months. Please try updating all of the installed mods.
Usual suspects: Twilight Forest (fixed with update), Minecraft Comes Alive Reborn (issue still open)

**Closed as completed by ZsoltMolnarrr** 2023-02-23 17:06 UTC
