### ISSUE TITLE
Seeing your own player model in front of you during combat animations(Inconsistent)

### ISSUE THREAD

**Issue by n0valey** [ZsoltMolnarrr/BetterCombat#211] opened 2023-02-22 19:55 UTC
**Minecraft version** - 1.19.2
**Mod loader** - forge 1.19.2 43.2.0
**Mod version** - 1.5.5 1.19
**I am using the latest version available** - for 1.19.2, yes

**Describe the bug**
In a multiplayer server, when two players are within 10~ blocks of each other, you can see your own better combat animations in first person, obscuring your vision. (me and my friends call it disassociating) The view is behind your player model and thus you can see your upper body phase in an out of itself when attacking.

**To Reproduce**
1. Play in a minecraft server with at least one other person
2. Be within 10 blocks of each other
3. You attack with a sword or weapon compatable with better combat animations
4. Is very inconsistent and doesn't cause a crash, is just distracting and intrusive
5. 
**Expected behavior**
To be able to see what you are attacking instead of the back of your own minecraft avatar's head

**Screenshots or video recordings**
it is very inconsistent, if/when it happens to me again i will take a screenshot and update this. 

**Additional context**
Me and my friends are playing on a pebblehost modded minecraft server with 4-5 people on at the same time, it could be an issue of server lag, but I have been tweaking it to make it less laggy and the problem still crops up every now and then. Again, it is a minor issue, that is inconsistent, will provide a screenshot/recording as soon as I can get one

**Comment by n0valey** [comment] 2023-02-25 01:50
![Screenshot_10](https://user-images.githubusercontent.com/126108875/221329573-bdfefdba-8717-4af2-bf70-c33dae62c5a7.png)
![Screenshot_9](https://user-images.githubusercontent.com/126108875/221329575-2e863465-d4a0-4e44-8823-5393dfe903f5.png)
![Screenshot_12](https://u
![Screenshot_8](https://user-images.githubusercontent.com/126108875/221329585-2e751543-911f-450a-9444-4de9ab0d3552.png)
ser-images.githubusercontent.com/126108875/221329578-a1c7a6ef-b053-47bf-981b-e0b9640ceda5.png)
![Screenshot_11](https://user-images.githubusercontent.com/126108875/221329579-fdee03aa-583a-49a6-a248-6f496dd285eb.png)

**Comment by ZsoltMolnarrr** [comment] 2023-04-07 11:22
Better Combat Discord FAQ

**Whenever I swing a weapon in First person, my head shows up and it  blocks the screen fully. How to fix?**
This kind of problem is typically caused by another mod that handles renderstates in a faulty way.
Many of these (formerly incompatible) mods have been fixed in the recent months. Please try updating all of the installed mods.
Usual suspects: Twilight Forest (fixed with update), Minecraft Comes Alive Reborn (issue still open)

**Closed as completed by ZsoltMolnarrr** 2023-04-07 11:22 UTC
