### ISSUE TITLE
[Forge 1.18.2] Two hits with one swing using a spear

### ISSUE THREAD

**Issue by huds2** [ZsoltMolnarrr/BetterCombat#72] opened 2022-08-25 18:26 UTC
Minecraft 1.18.2
Forge 40.1.68
Better Combat 1.1.0

When using the spear it seems like the game does a vanilla attack, and when the animation finishes, it does a second attack. The issue doesn't persist if you hold the attack button instead of clicking it repeatedly. Issue occurred when using Epic Knights 6.3 mod.
The fallback config for weapons that behave as spears was as follows:
```
{
      "item_id_regex": "spear|lance|whisper_of_the_abyss|pike|ranseur|ahlspiess|pitchfork|guisarme",
      "weapon_attributes": "bettercombat:spear"
},
```
https://user-images.githubusercontent.com/74903224/186741029-bc7eddb1-dd48-4247-91f2-fd294ef82170.mp4
(In the video I was repeatedly clicking the m1 button)

The bug seems to happen only in certain range. Not sure if it is related only to spears but I wasn't able to reproduce it with other types of weapons

**Comment by ZsoltMolnarrr** [comment] 2022-08-25 18:55
I am fairly certain, the source of the issue is the custom attack reach implementation of Epic Knights mod.
Some mods have conflicting behaviour which is impossible to resolve on the side of Better Combat, because Better Combat is a lower level mod, an API that doesn't reference any other content oriented mods.

Conflicting things can be found here.
https://github.com/ZsoltMolnarrr/BetterCombat#prerequisite

Unfortunately the only way to resolve is to start partnership with the authors of Epic Knights and fully adapt this mod. (Its not much work they just need to disable a few features to fully rely on Better Combat).

I am closing the issue since nothing can be done on this side.

**Closed as completed by ZsoltMolnarrr** 2022-08-25 18:55 UTC
